### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getPreference()Lcom/moengage/core/internal/storage/preference/SharedPrefHelper

### ISSUE THREAD

**Issue by rethinavelsmitch** [moengage/Android-Sample#14]
java.lang.NoSuchMethodError: No virtual method getPreference()Lcom/moengage/core/internal/storage/preference/SharedPrefHelper; in class Lcom/moengage/core/internal/model/database/DataAccessor; or its super classes (declaration of 'com.moengage.core.internal.model.database.DataAccessor' appears in /data/app/~~7BYXatOstpu4LVICF29rDQ==/com.mysmitch.care-FaGGyPP_Uk80IInVbYk56g==/base.apk!classes37.dex)
	at com.moengage.inapp.internal.repository.local.LocalRepositoryImpl.getLastHtmlAssetsDeleteTime(LocalRepositoryImpl.kt:628)
	at com.moengage.inapp.internal.repository.InAppRepository.getLastHtmlAssetsDeleteTime(Unknown Source:2)
	at com.moengage.inapp.internal.tasks.AppOpenHandler.shouldClearHtmlAssets(AppOpenHandler.kt:97)
	at com.moengage.inapp.internal.tasks.AppOpenHandler.onAppOpen(AppOpenHandler.kt:44)
	at com.moengage.inapp.internal.InAppBuilderKt.getAppOpenJob$lambda-8(InAppBuilder.kt:131)
	at com.moengage.inapp.internal.InAppBuilderKt.$r8$lambda$Nj42CMsTur3oYpPddQaiFgWgepw(Unknown Source:0)
	at com.moengage.inapp.internal.InAppBuilderKt$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at com.moengage.core.internal.executor.AsyncHandler.execute$lambda-0(AsyncHandler.kt:61)
	at com.moengage.core.internal.executor.AsyncHandler.$r8$lambda$YrIEPrD90X5dmlVOdFMsHSypgnk(Unknown Source:0)
	at com.moengage.core.internal.executor.AsyncHandler$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
win=Window{80a55a0 u0 Splash Screen com.mysmitch.care EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5867 com.android.server.wm.ActivityRecord.destroySurfaces:5848 com.android.server.wm.WindowState.onExitAnimationDone:5992 com.android.server.wm.WindowStateAnimator.onAnimationFinished:242 com.android.server.wm.WindowState.onAnimationFinished:6245 com.android.server.wm.WindowContainer$$ExternalSyntheticLambda0.onAnimationFinished:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0$SurfaceAnimator:113 

I am getting crashes 

    compileSdk 33
    defaultConfig {
        applicationId "com.mysmitch.care"
        minSdkVersion 29
        maxSdkVersion 33
        targetSdkVersion 33
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true

    //MoEngage
    implementation 'com.moengage:moe-android-sdk:12.9.01'
    implementation(moengage.core)
    implementation(moengage.inapp)

**Comment by Jad-Jbara** [comment]
Can confirm happening on `"com.moengage:moe-android-sdk:12.9.03"` as well.
`package.json`:
```
"react-native": "0.72.5",
"react-native-moengage": "^8.5.3",
```

Reverting back to: `implementation "com.moengage:moe-android-sdk:12.6.01"` works.

**Comment by vipinmoe** [comment]
**Here is the call summary as discussed:** 
 
The issue was the incompatibility of the MoE SDK dependencies.

**Comment by Jad-Jbara** [comment]
@vipinmoe can you please clarify? Because we are facing the same issue when we upgrade MoEngage version and the androidx versions in our project . Following the installation docs doesn't work without having to modify the androidx dependencies versions.
