### ISSUE TITLE
Crashing while fetching fetching Unread message count.

### ISSUE THREAD

**Issue by happysingh23828** [moengage/Android-Sample#5]
It's crashing while getting getting unread count of notification center.

```
 //Moengage
    api "com.moengage:moe-android-sdk:11.2.01"
    api "com.moengage:addon-inbox:6.0.2"
    api "com.moengage:inbox-ui:1.0.00"
    api "com.moengage:inbox-core:1.0.00"
    api 'androidx.legacy:legacy-support-v4:1.0.0'
    api "androidx.lifecycle:lifecycle-process:2.3.1"


```

```
2021-06-04 01:02:59.624 17853-17853/com.bitclass.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bitclass.android, PID: 17853
    java.lang.NoSuchMethodError: No static method getContentUri(Landroid/content/Context;)Landroid/net/Uri; in class Lcom/moengage/core/internal/storage/database/contract/InboxMessageContract$InboxMessageEntity; or its super classes (declaration of 'com.moengage.core.internal.storage.database.contract.InboxMessageContract$InboxMessageEntity' appears in /data/app/com.bitclass.android-jVzQJ7SqdZaGL3kul5Gacw==/base.apk!classes20.dex)
        at com.moengage.addon.inbox.internal.repository.local.LocalRepositoryImpl.<init>(LocalRepositoryImpl.kt:34)
        at com.moengage.addon.inbox.internal.Injection.getRepository(Injection.kt:31)
        at com.moengage.addon.inbox.MoEInboxHelper.getUnClickedMessagesCount(MoEInboxHelper.kt:135)
        at com.bitclass.android.agora.activities.DrawerBaseActivity.setNotificationBadge(DrawerBaseActivity.kt:147)
        at com.bitclass.android.agora.activities.DrawerBaseActivity.onResume(DrawerBaseActivity.kt:141)
        at com.bitclass.android.studenthome.StudentHomeActivity.onResume(StudentHomeActivity.kt:300)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
        at android.app.Activity.performResume(Activity.java:8050)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4260)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4302)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by umangmoe** [comment]
`api "com.moengage:addon-inbox:6.0.2"`

Is not supported with SDK version `11.2.01`. Remove the above dependency and you should be able to resolve the issue.

**Comment by happysingh23828** [comment]
Yes, I checked the migration doc and updated SDK , Thanks @umangmoe.
