### ISSUE TITLE
Release Build Crashing on launch with  "java.lang.AbstractMethodError" error

### ISSUE THREAD

**Issue by SyedAtifAli** [moengage/Android-Sample#8]
Hi so i downloaded this sample app and made a signed release build and when i launch tha apk it just crashes with the following error:
```

2022-03-31 08:51:47.413 31613-31613/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.moengage.example, PID: 31613
    java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
        at com.moengage.core.internal.CoreController.addObserver(CoreController.kt:132)
        at com.moengage.core.internal.CoreController.registerProcessLifecycleObserver(CoreController.kt:115)
        at com.moengage.core.internal.CoreController.registerApplicationCallbacks$core_release(CoreController.kt:100)
        at com.moengage.core.internal.initialisation.InitialisationHandler.initialiseSdk(InitialisationHandler.kt:69)
        at com.moengage.core.MoEngage$Companion.initSdk(MoEngage.kt:271)
        at com.moengage.core.MoEngage$Companion.initialiseDefaultInstance(MoEngage.kt:283)
        at com.moengage.example.MoEngageDemoApplication.onCreate(MoEngageDemoApplication.kt:29)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1199)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6878)
        at android.app.ActivityThread.access$1500(ActivityThread.java:240)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2052)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7853)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
```
Gradle version tried - 7.1.1 , 7.2 and 7.4.1 but it crashes in all of them

**Comment by SyedAtifAli** [comment]
The only working fix I found is to upgrade minsdk from 21 to 24, is there any other solution to this? or are we going to lose 3 android api version worth of support for our app !!

**Comment by shybalwombat** [comment]
Hey there,

Don't know if this is useful now, the problem is with their SDK version

`implementation("com.moengage:moe-android-sdk:12.2.01")`

should now work with this SDK version or higher
